
source "http://geminabox:9292/"

# Specify your gems dependencies in predictor.gemspec
gemspec

gem "trueskill", git: "https://github.com/benjaminleesmith/trueskill", ref: "e404f45af5b3fb86982881ce064a9c764cc6a901"

